### ISSUE TITLE
Every new block generated, a corresponding new miner address is generated

### ISSUE THREAD

**Issue by TuyenVo-MetaDap** [bnb-chain/bas-template-bsc#5]
I built a BAS network with only 3 validators (Ankr guide) and I noticed that for every new block generated, a corresponding new miner address is generated.

This is different from the BNB mainnet, all blocks are generated only by defined validators.

Can you help me understand why there is this difference?

Thank you so much!

**Comment by 0xLyon** [comment]
Hi there, can you provide more details to how you configured your BAS config.toml file, as per the explained parameters here (https://github.com/bnb-chain/bas-devnet-setup) allows you to set the initial validators and the amount of validators that you would like your BAS network to have.

**Comment by ThaiTuyen** [comment]
Hi @0xLyon 
Thanks for your reply, I can set the initial validators and it not problems, But i found that for every new block is generated ( every 3s ), The Miner address is not in the validators list, it is a new address is generated

**Comment by 0xLyon** [comment]
Please share some extra details of your setup and what you are seeing with regards tot he different miner addresses. Please try share as detailed as possible, so we can have one of the developers look into this.

**Comment by TuyenVo-MetaDap** [comment]
Hi @0xLyon I found that the cause of this issue is wrong seting in  blockscout explorer
I will close this issue, thanks for your support

**Comment by crpodev** [comment]
> Hi @0xLyon I found that the cause of this issue is wrong seting in blockscout explorer I will close this issue, thanks for your support

can you elaborate on what the cause was? i am facing the same issue. thanks in advance.

**Comment by ThaiTuyen** [comment]
Hi @crpodev BAS use consensus is "paliar", so we need config BLOCK_TRANSFORMER as base ( not clique)
you can refer: https://docs.blockscout.com/for-developers/information-and-settings/env-variables#indexer-management
